# Generated by Django 3.1.2 on 2020-10-05 22:58

import demo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('permission', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type_field', models.CharField(db_column='type', max_length=2, validators=[demo.models.validate_type], verbose_name='type')),
                ('inception_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.client')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.fund')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('return_field', models.DecimalField(db_column='return', decimal_places=2, max_digits=11, verbose_name='return')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.investment')),
            ],
        ),
    ]
